classOrder = ["RotatedRegion3"]
title = "FastRotatedRegion3"
changelog = true
gitSourceBranch = "main"

[docusaurus]
tagline = "A faster implementation of EgoMoose's RotatedRegion3"

[[navbar.items]]
href = "https://discord.gg/nhDpg96Srt"
label = "Discord"
position = "right"

[[navbar.items]]
href = "https://discord.gg/luau"
label = "Luau Discord"
position = "right"

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Improved Performance"
description = "Performance has been improved around 25% over the original source."
